/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import products.*;
import operation.*;
/**
 *
 * @author Juan Miguel
 */
public class EditProductFrame extends javax.swing.JFrame {
    Object objArr[];
    boolean allGood[] = new boolean[7];
    ArraysDataStruct productList;
    InventoryDisplay inventoryList;
    int oldRefNum;
    
    /**
     * Creates new form AddProductFrame
     */
    public EditProductFrame(ArraysDataStruct productList, InventoryDisplay inventoryList, Product oldProduct) {
        objArr = new Object[7];
        this.productList = productList;
        this.inventoryList = inventoryList;
        oldRefNum = oldProduct.getRefNum();
        allGood[5] = true;  //set status
        initComponents();
        brandTextF.setText(oldProduct.getBrand());
        deviceTextF.setText(oldProduct.getDeviceType());
        modelTextF.setText(oldProduct.getModel());
        priceTextF.setText(String.valueOf(oldProduct.getPrice()));
        qtyTextF.setText(String.valueOf(oldProduct.getQuantity()));
        statusTextF.setText(oldProduct.getStatus());
        refNumTextF.setText(String.valueOf(oldProduct.getRefNum()));
    }
    
    public boolean checkAllGood() {
        for(int i=0; i<7; i++) 
            if(!allGood[i])
                return false;
        confirmButton.setEnabled(true);
        return true;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        brandTextF = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        deviceTextF = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        modelTextF = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        priceTextF = new javax.swing.JTextField();
        qtyTextF = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        statusTextF = new javax.swing.JTextField();
        statusTextF.setEnabled(false);
        jLabel8 = new javax.swing.JLabel();
        refNumTextF = new javax.swing.JTextField();
        invalidPriceLabel = new javax.swing.JLabel();
        invalidPriceLabel.setVisible(false);
        invalidQtyLabel = new javax.swing.JLabel();
        invalidQtyLabel.setVisible(false);
        invalidRefNumLabel = new javax.swing.JLabel();
        invalidRefNumLabel.setVisible(false);
        addedPrice = new javax.swing.JLabel();
        addedPrice.setVisible(false);
        addedDeviceType = new javax.swing.JLabel();
        addedDeviceType.setVisible(false);
        addedModel = new javax.swing.JLabel();
        addedModel.setVisible(false);
        addedStatus = new javax.swing.JLabel();
        addedStatus.setVisible(false);
        addedQty = new javax.swing.JLabel();
        addedQty.setVisible(false);
        addedRefNum = new javax.swing.JLabel();
        addedRefNum.setVisible(false);
        addedBrand = new javax.swing.JLabel();
        addedBrand.setVisible(false);
        confirmButton = new javax.swing.JButton();
        confirmButton.setEnabled(false);
        cancelButton = new javax.swing.JButton();
        refNumLabel = new javax.swing.JLabel();
        refNumLabel.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setToolTipText("");
        jPanel1.setName("Edit Product"); // NOI18N
        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Edit the Product data in the corresponding Fields:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_START;
        gridBagConstraints.insets = new java.awt.Insets(5, 20, 5, 20);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel3.setText("Brand:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 9);
        jPanel1.add(jLabel3, gridBagConstraints);

        brandTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                brandTextFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(brandTextF, gridBagConstraints);

        jLabel2.setText("Device Type:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 9);
        jPanel1.add(jLabel2, gridBagConstraints);

        deviceTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deviceTextFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(deviceTextF, gridBagConstraints);

        jLabel4.setText("Model:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 9);
        jPanel1.add(jLabel4, gridBagConstraints);

        modelTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modelTextFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(modelTextF, gridBagConstraints);

        jLabel5.setText("Price:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 9);
        jPanel1.add(jLabel5, gridBagConstraints);

        priceTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                priceTextFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(priceTextF, gridBagConstraints);

        qtyTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                qtyTextFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(qtyTextF, gridBagConstraints);

        jLabel6.setText("Quantity:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 9);
        jPanel1.add(jLabel6, gridBagConstraints);

        jLabel7.setText("Status:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 9);
        jPanel1.add(jLabel7, gridBagConstraints);

        statusTextF.setToolTipText("");
        statusTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                statusTextFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(statusTextF, gridBagConstraints);

        jLabel8.setText("Reference Num:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 9);
        jPanel1.add(jLabel8, gridBagConstraints);

        refNumTextF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                refNumTextFActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.insets = new java.awt.Insets(2, 4, 2, 4);
        jPanel1.add(refNumTextF, gridBagConstraints);

        invalidPriceLabel.setForeground(new java.awt.Color(255, 0, 0));
        invalidPriceLabel.setText("Invalid Input");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        jPanel1.add(invalidPriceLabel, gridBagConstraints);

        invalidQtyLabel.setForeground(new java.awt.Color(255, 0, 0));
        invalidQtyLabel.setText("Invalid Input");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        jPanel1.add(invalidQtyLabel, gridBagConstraints);

        invalidRefNumLabel.setForeground(new java.awt.Color(255, 0, 0));
        invalidRefNumLabel.setText("Invalid Input");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        jPanel1.add(invalidRefNumLabel, gridBagConstraints);

        addedPrice.setText("Edited!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 4;
        jPanel1.add(addedPrice, gridBagConstraints);

        addedDeviceType.setText("Edited!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 2;
        jPanel1.add(addedDeviceType, gridBagConstraints);

        addedModel.setText("Edited!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 3;
        jPanel1.add(addedModel, gridBagConstraints);

        addedStatus.setText("Added!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 6;
        jPanel1.add(addedStatus, gridBagConstraints);

        addedQty.setText("Edited!");
        addedQty.setToolTipText("");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 5;
        jPanel1.add(addedQty, gridBagConstraints);

        addedRefNum.setText("Edited!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        jPanel1.add(addedRefNum, gridBagConstraints);

        addedBrand.setText("Edited!");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 1;
        jPanel1.add(addedBrand, gridBagConstraints);

        confirmButton.setText("Confirm");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 0);
        jPanel1.add(confirmButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(10, 0, 5, 4);
        jPanel1.add(cancelButton, gridBagConstraints);

        refNumLabel.setForeground(new java.awt.Color(255, 0, 0));
        refNumLabel.setText("Ref Num is used");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 3;
        gridBagConstraints.gridy = 7;
        jPanel1.add(refNumLabel, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void brandTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_brandTextFActionPerformed
        objArr[0] = brandTextF.getText();
        allGood[0] = true;
        addedBrand.setVisible(true);
        checkAllGood();
    }//GEN-LAST:event_brandTextFActionPerformed

    private void deviceTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deviceTextFActionPerformed
        objArr[1] = brandTextF.getText();
        allGood[1] = true;
        addedDeviceType.setVisible(true);
        checkAllGood();
    }//GEN-LAST:event_deviceTextFActionPerformed

    private void modelTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modelTextFActionPerformed
        objArr[2] = modelTextF.getText();
        allGood[2] = true;
        addedModel.setVisible(true);
        checkAllGood();
    }//GEN-LAST:event_modelTextFActionPerformed

    private void priceTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_priceTextFActionPerformed
        try {
            double test = Double.parseDouble(priceTextF.getText());
            if(test<0)
                throw new NumberFormatException();
            objArr[3] = test;
            allGood[3] = true;
            checkAllGood();
        }
        catch (NumberFormatException e) {
            allGood[3] = false;
        }
        addedPrice.setVisible(allGood[3]);
        invalidPriceLabel.setVisible(!allGood[3]);
    }//GEN-LAST:event_priceTextFActionPerformed

    private void qtyTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_qtyTextFActionPerformed
        try {
            int test = Integer.parseInt(qtyTextF.getText());
            if(test<0)
                throw new NumberFormatException();
            if(test>10)
                statusTextF.setText("Available");
            else if(test>0)
                statusTextF.setText("Running Out");
            else
                statusTextF.setText("Empty");
            objArr[4] = test;
            allGood[4] = true;
            checkAllGood();
        }
        catch (NumberFormatException e) {          
            statusTextF.setText("");
            allGood[4] = false;
        }
        addedQty.setVisible(allGood[4]);
        invalidQtyLabel.setVisible(!allGood[4]);
    }//GEN-LAST:event_qtyTextFActionPerformed

    private void statusTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_statusTextFActionPerformed
        objArr[5] = statusTextF.getText();
        allGood[5] = true;
        addedStatus.setVisible(true);
        checkAllGood();
    }//GEN-LAST:event_statusTextFActionPerformed

    private void refNumTextFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_refNumTextFActionPerformed
        try {
            int test = Integer.parseInt(refNumTextF.getText());
            if(productList.checkEqualRefNum(test)) {
                refNumLabel.setVisible(true);
                allGood[6] = false;
                addedRefNum.setVisible(allGood[6]);
                return;
            }
            else {
                refNumLabel.setVisible(false);
            }
            objArr[6] = test;
            allGood[6] = true;
            checkAllGood();
        }
        catch (NumberFormatException e) {           
            allGood[6] = false;
        }
        addedRefNum.setVisible(allGood[6]);
        invalidRefNumLabel.setVisible(!allGood[6]);
    }//GEN-LAST:event_refNumTextFActionPerformed

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        productList.remove(oldRefNum);
        productList.add(new Product(objArr));
        inventoryList.deleteRow(oldRefNum);
        inventoryList.addTableRow(objArr);
        this.dispose();
    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(EditProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(EditProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(EditProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(EditProductFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new EditProductFrame(null, null, null).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel addedBrand;
    private javax.swing.JLabel addedDeviceType;
    private javax.swing.JLabel addedModel;
    private javax.swing.JLabel addedPrice;
    private javax.swing.JLabel addedQty;
    private javax.swing.JLabel addedRefNum;
    private javax.swing.JLabel addedStatus;
    private javax.swing.JTextField brandTextF;
    private javax.swing.JButton cancelButton;
    private javax.swing.JButton confirmButton;
    private javax.swing.JTextField deviceTextF;
    private javax.swing.JLabel invalidPriceLabel;
    private javax.swing.JLabel invalidQtyLabel;
    private javax.swing.JLabel invalidRefNumLabel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField modelTextF;
    private javax.swing.JTextField priceTextF;
    private javax.swing.JTextField qtyTextF;
    private javax.swing.JLabel refNumLabel;
    private javax.swing.JTextField refNumTextF;
    private javax.swing.JTextField statusTextF;
    // End of variables declaration//GEN-END:variables
}
