/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package userinterface;

import admin_account.*;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author Juan Miguel
 */
public class LogInFrame extends javax.swing.JFrame {
    String admin_accountsFile = "./src/database/admin_accounts.txt";
    String employeeFile = "./src/database/employee.txt";
    String userAuth;
    ArrayList<AdminAccount> accounts;
    /**
     * Creates new form LogInFrame
     */
    public LogInFrame() {
        accounts = Utilities.accessAdminAccounts(admin_accountsFile);
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                initComponents();
            }
        });
    }
    
    public synchronized void makeWait() throws InterruptedException {
        wait();
    }
    
    public synchronized void awake() {
        notifyAll();
    }
    
    public String getUserAuth() {
        return userAuth;
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        usernameTextF = new javax.swing.JTextField();
        passwordTextF = new javax.swing.JTextField();
        logInEmpButton = new javax.swing.JButton();
        cancelButton = new javax.swing.JButton();
        logInAdminButton = new javax.swing.JButton();
        wrongEmpLabel = new javax.swing.JLabel();
        wrongEmpLabel.setVisible(false);
        wrongAdminLabel = new javax.swing.JLabel();
        wrongAdminLabel.setVisible(false);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new javax.swing.BoxLayout(getContentPane(), javax.swing.BoxLayout.LINE_AXIS));

        jPanel1.setLayout(new java.awt.GridBagLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Enter User Authorization");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.insets = new java.awt.Insets(10, 10, 10, 10);
        jPanel1.add(jLabel1, gridBagConstraints);

        jLabel2.setText("Username:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 5);
        jPanel1.add(jLabel2, gridBagConstraints);

        jLabel3.setText("Password: ");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 6, 5);
        jPanel1.add(jLabel3, gridBagConstraints);

        usernameTextF.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 5, 0);
        jPanel1.add(usernameTextF, gridBagConstraints);

        passwordTextF.setColumns(12);
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.insets = new java.awt.Insets(5, 0, 6, 0);
        jPanel1.add(passwordTextF, gridBagConstraints);

        logInEmpButton.setText("Log in as Employee");
        logInEmpButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInEmpButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(5, 5, 5, 5);
        jPanel1.add(logInEmpButton, gridBagConstraints);

        cancelButton.setText("Cancel");
        cancelButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cancelButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 1;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.LINE_END;
        gridBagConstraints.insets = new java.awt.Insets(0, 0, 0, 5);
        jPanel1.add(cancelButton, gridBagConstraints);

        logInAdminButton.setText("Log in as Admin");
        logInAdminButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logInAdminButtonActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.insets = new java.awt.Insets(0, 5, 0, 0);
        jPanel1.add(logInAdminButton, gridBagConstraints);

        wrongEmpLabel.setForeground(new java.awt.Color(255, 0, 0));
        wrongEmpLabel.setText("Wrong Employee Credentials");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel1.add(wrongEmpLabel, gridBagConstraints);

        wrongAdminLabel.setForeground(new java.awt.Color(255, 0, 0));
        wrongAdminLabel.setText("Admin Account not Found");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        jPanel1.add(wrongAdminLabel, gridBagConstraints);

        getContentPane().add(jPanel1);

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logInAdminButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInAdminButtonActionPerformed
        String username = usernameTextF.getText(), password = passwordTextF.getText();
        if(Utilities.searchAdminAccount(accounts, username, password)) {
            userAuth = "Admin";
            awake();
            this.dispose();
        }
        else {
            wrongAdminLabel.setVisible(true);
        }
    }//GEN-LAST:event_logInAdminButtonActionPerformed

    private void cancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cancelButtonActionPerformed
        userAuth = "cancel";
        awake();
        this.dispose();
    }//GEN-LAST:event_cancelButtonActionPerformed

    private void logInEmpButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logInEmpButtonActionPerformed
        String username = usernameTextF.getText(), password = passwordTextF.getText();
        if(Utilities.checkEmployeeCredentials(employeeFile, username, password)) {
            userAuth = "Employee";
            awake();
            this.dispose();
        }
        else {
            wrongEmpLabel.setVisible(true);
        }
    }//GEN-LAST:event_logInEmpButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LogInFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new LogInFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton cancelButton;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logInAdminButton;
    private javax.swing.JButton logInEmpButton;
    private javax.swing.JTextField passwordTextF;
    private javax.swing.JTextField usernameTextF;
    private javax.swing.JLabel wrongAdminLabel;
    private javax.swing.JLabel wrongEmpLabel;
    // End of variables declaration//GEN-END:variables
}
